name: code_secure_flutter
description: "A Set of rules to ensure secure coding practices in Flutter applications."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  analyzer: 'any'
  analyzer_plugin: '>=0.10.0'
  custom_lint_builder: '>=0.5.0'
  collection: ^1.19.1
  # ollama_dart: ^0.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  custom_lint: any

